services:
  # Backend service
  - type: web
    name: flashcards-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: flashcards-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://flashcards-backend.onrender.com