services:
  - type: web
    name: flashcards-assessment-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:server
    envVars:
      - key: PORT
        value: 10000

  - type: static
    name: flashcards-assessment-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://flashcards-assessment-backend.onrender.com